### PR TITLE
More note input examples.

### PR DESCRIPTION
**Pull request by erlend-aasland**
I've added a short example of how to write chords. I also started on a "variables example", but I ditched it, because I think the poster might be too cluttered. Let me know if you want me to add it nevertheless.

Note, if you merge #7, I would propose to change the heading added in commit 2a83fe4 from `Note Entry` to `Chord Entry`.

### CODE REVIEW

**Review by jpvoigt — APPROVED** [review]
This is a good example.

**Comment by erlend-aasland** [comment]
Thanks, @jpvoigt!

**Comment by jpvoigt** [comment]
@erlend-aasland Could you add a PR for the variable usage? I am aligning the blocks, so that there is room above the examples.

**Comment by erlend-aasland** [comment]
Yes, comin' up in two minutes…

**Pull request merged**
