### PR TITLE
Reformulate text input

### PR DESCRIPTION
**Pull request by erlend-aasland**
Proposed reformulation of `Text Input` section. Let me know what you think, @jpvoigt & @uliska.

### CODE REVIEW

**Comment by jpvoigt** [comment]
I like the new text and merged it in staging branch. If @uliska doesn't reject, I will merge.

**Review by jpvoigt — APPROVED** [review]
This text much more appealing in the context of the poster.  The former was just taken from the website.

**Comment by uliska** [comment]
+1

**Comment by jpvoigt** [comment]
I merged the text via the staging branch

**Comment by erlend-aasland** [comment]
Great, thanks!

**Pull request closed without merging**
