### PR TITLE
Normalize quotation marks.

### PR DESCRIPTION
**Pull request by erlend-aasland**
Looks nicer, IMHO. Feel free to disregard this PR if you disagree.

### CODE REVIEW

**Comment by jpvoigt** [comment]
I like it and merged it into a staging branch so that Urs can also reply.

**Comment by jpvoigt** [comment]
I think @uliska  changed to the french quotation mark for some reason. I am not passionate about it.

**Comment by uliska** [comment]
Just for the record: I changed the quotations from both wrong to the respective English and *German* versions. French would be `« ... »`. But I'm fine with consistently using the English quotes from the main text, regardless of the title's language.

**Comment by jpvoigt** [comment]
O dear, yes, those are the German ones. I am only used to „“ ... 
Now I prefer English quotes for all. Sorry for the noise!

**Pull request merged**
